name: ficha3
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mysql1: ^0.20.0
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  firebase_core: ^2.27.2
  cloud_firestore: ^4.15.10
  provider: ^6.1.2
  carousel_slider: ^4.0.0
  sqflite: ^2.3.3
  path: ^1.9.0
  geolocator: ^11.0.0
  geocoding: ^2.0.1
  table_calendar: ^3.1.1
  intl: ^0.19.0
  flutter_speed_dial: ^7.0.0
  flutter_animated_icons: ^1.0.1
  path_provider: ^2.1.3
  url_launcher: ^6.2.6
  url_launcher_android: ^6.3.1
  permission_handler: ^11.3.1
  flutter_rating_bar: ^4.0.1
  flutter_keyboard_visibility: ^6.0.0
  google_maps_flutter: ^2.6.1
  photo_view: ^0.15.0
  flutter_slidable: ^3.1.0
  swipe_to: ^1.0.6
  flutter_swipe_action_cell: ^3.1.3
  image_picker: ^1.1.1
  connectivity_plus: ^6.0.3
  flare_flutter: ^3.0.2
  flutter_facebook_auth: ^7.0.0
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/PAGINA_DE_LOGIN/icons/
    - assets/images/evento_fut.jpg
    - assets/images/evento_ciclismo.jpeg
    - assets/images/evento_padle.jpg
    - assets/images/logotipo-softinsa.png
    - assets/images/evento_tenis.jpg
    - assets/images/rafa.jpg
    - assets/images/area_saude.png
    - assets/images/area_alojamento.png
    - assets/images/area_desporto.png
    - assets/images/area_formação.png
    - assets/images/area_gastronomia.png
    - assets/images/area_lazer.png
    - assets/images/area_transportes.png
    - assets/images/ver_info.png
    - assets/images/235.jpg
    - assets/images/forum.jpg
    - assets/images/hotel.jpg
    - assets/images/rossio.jpg
    - assets/images/keb.webp
    - assets/images/fontelo.jpg
    - assets/images/hospital.png
    - assets/images/restaurante.jpg
    - assets/images/campodefutbol.jpg
    - assets/images/pessoa1.jpeg
    - assets/images/pessoa2.jpeg
    - assets/images/pessoa3.jpeg
    - assets/images/pessoa4.jpg
    - assets/images/partilha1.png
    - assets/images/partilha2.png
    - assets/images/partilha3.jpg
    - assets/images/evento_alojamento.png
    - assets/images/evento_formacao.jpg
    - assets/images/evento_gastronomia.jpg
    - assets/images/evento_saude.jpeg
    - assets/images/evento_transprotes.jpg
    - assets/images/evento_turismo.jpg
    - assets/images/local_alojamento.jpg
    - assets/images/local_formacao.png
    - assets/images/local_lazer.jpg
    - assets/images/local_transportes.png
    - assets/images/pessoa5.jpg
    - assets/images/pessoa6.jpg
    - assets/images/pessoa7.jpeg
    - assets/images/pessoa8.jpg
    - assets/images/pessoa9.jpg
    - assets/images/partilha_alojamento.jpg
    - assets/images/partilha_formacao.jpg
    - assets/images/partilha_gastronomia.jpg
    - assets/images/partilha_lazer.jpg
    - assets/images/partilha_saude.png
    - assets/images/partilha_transportes.jpg
    - assets/images/icons_dos_topicos/bola.png
    - assets/images/icons_dos_topicos/topico_ciclismo.png
    - assets/images/icons_dos_topicos/topico_cursos.png
    - assets/images/icons_dos_topicos/topico_feira_turismo.png
    - assets/images/icons_dos_topicos/topico_feiras.png
    - assets/images/icons_dos_topicos/topico_festival.png
    - assets/images/icons_dos_topicos/topico_mobilidade.png
    - assets/images/icons_dos_topicos/topico_nutricao.png
    - assets/images/icons_dos_topicos/topico_tenis.png
    - assets/images/icons_dos_topicos/topico_padel.png
    - assets/images/no_events.png
    - assets/images/user_padrao.jpg
    - assets/images/fundo_susana.jpg
    - assets/images/fundo_rafa.jpg
    - assets/images/fav_alojamento.png
    - assets/images/fav_desporto.png
    - assets/images/fav_formacao.png
    - assets/images/fav_lazer.png
    - assets/images/fav_restaurant.png
    - assets/images/fav_saude.png
    - assets/images/fav_transportes.png
    - assets/images/grupodofut.jpg
    - assets/images/grupo_tenis.jpg
    - assets/images/grupo_padel.png
    - assets/images/futebol2.jpeg
    - assets/images/grupo_ciclismo.jpeg
    - assets/images/icon_destaque.png
    - assets/images/icon_maisnovos.png
    - assets/images/sem_resultados.png
    - assets/images/partilha_ciclismo.png
    - assets/images/images_dos_topicos/fut_1.png
    - assets/images/images_dos_topicos/fut_2.png
    - assets/images/images_dos_topicos/fut_3.png
    - assets/images/imagens_local/fontelo_1.jpg
    - assets/images/imagens_local/fontelo_2.png
    - assets/images/imagens_local/fontelo_3.png
    - assets/images/imagens_local/fontelo_4.png
    - assets/images/imagens_local/fontelo_5.png
    - assets/images/imagens_local/fontelo_6.png
    - assets/images/sem_imagem.png
    - assets/images/imagens_partilhasfotos/partilha_basket.jpg
    - assets/images/sem_grupos.png
    - assets/images/imagens_grupos/tenis_1.png
    - assets/images/imagens_grupos/sem_capa.png
    - assets/images/imagens_grupos/sem_avatar.png
    - assets/images/imagens_perfilusers/fundo_1.png
    - assets/images/imagens_perfilusers/fundo_2.png
    - assets/images/imagens_perfilusers/fundo_3.png
    - assets/images/sem_menbros_pendentes.png
    - assets/images/circulo_progresso.png
    - assets/images/centros/Fundão.png
    - assets/images/centros/Portalegre.png
    - assets/images/centros/Tomar.png
    - assets/images/centros/VilaReal.png
    - assets/images/centros/Viseu.png
    - assets/images/sem_wifi.png
    - assets/images/sem_mesagens.png
    - assets/images/sem_partilhas.png
    - assets/images/icons_dos_topicos/topico_atletismo.png
    - assets/images/icons_dos_topicos/topico_voleibol.png
    - assets/images/icons_dos_topicos/topico_basket.png
    - assets/images/icons_dos_topicos/topico_fitness.png
    - assets/images/icons_dos_topicos/topico_ginasio.png
    - assets/images/images_dos_topicos/atletismo_1.png 
    - assets/images/images_dos_topicos/atletismo_2.png  
    - assets/images/images_dos_topicos/atletismo_3.png   
    - assets/images/images_dos_topicos/basket_1.png 
    - assets/images/images_dos_topicos/basket_2.png
    - assets/images/images_dos_topicos/basket_3.png  
    - assets/images/images_dos_topicos/ciclismo_1.png 
    - assets/images/images_dos_topicos/ciclismo_2.png 
    - assets/images/images_dos_topicos/ciclismo_3.png 
    - assets/images/images_dos_topicos/cursos_1.png 
    - assets/images/images_dos_topicos/cursos_2.png
    - assets/images/images_dos_topicos/cursos_3.png
    - assets/images/images_dos_topicos/feiras_1.png
    - assets/images/images_dos_topicos/feiras_2.png
    - assets/images/images_dos_topicos/feiras_3.png
    - assets/images/images_dos_topicos/feiras_aloj_1.png
    - assets/images/images_dos_topicos/feiras_aloj_2.png
    - assets/images/images_dos_topicos/feiras_aloj_3.png
    - assets/images/images_dos_topicos/festival_1.png
    - assets/images/images_dos_topicos/festival_2.png
    - assets/images/images_dos_topicos/festival_3.png
    - assets/images/images_dos_topicos/fitness_1.png
    - assets/images/images_dos_topicos/fitness_2.png
    - assets/images/images_dos_topicos/fitness_3.png
    - assets/images/images_dos_topicos/ginasios_1.png
    - assets/images/images_dos_topicos/ginasios_2.png
    - assets/images/images_dos_topicos/ginasios_3.png
    - assets/images/images_dos_topicos/mobilidade_1.png
    - assets/images/images_dos_topicos/mobilidade_2.png
    - assets/images/images_dos_topicos/mobilidade_3.png
    - assets/images/images_dos_topicos/nutricao_1.png
    - assets/images/images_dos_topicos/nutricao_2.png
    - assets/images/images_dos_topicos/nutricao_3.png
    - assets/images/images_dos_topicos/padle_1.png
    - assets/images/images_dos_topicos/padle_2.png
    - assets/images/images_dos_topicos/padle_3.png
    - assets/images/images_dos_topicos/tenis_1.png
    - assets/images/images_dos_topicos/tenis_2.png
    - assets/images/images_dos_topicos/tenis_3.png
    - assets/images/images_dos_topicos/voleibol_1.png
    - assets/images/images_dos_topicos/voleibol_2.png
    - assets/images/images_dos_topicos/voleibol_3.png
    - assets/images/local_vermapa.png












